config/routes.rb
Travelpatch::Application.routes.draw do
  resources :trip_destinations
  resources :trips
  resources :destinations

  get "users/new"

  get "users/create"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "trips/index"

  get "destinations/index"

  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "trip_list" => "trips#index", :as => "trip_list"

  get "select_destinations" => "destinations#index", :as => "select_destinations"

  root :to => "users#new"

  resources :users
  resources :sessions
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  attr_accessible :creator, :end_date, :start_date, :trip_description, :trip_name, :user_id

  belongs_to :user 
  has_many :destinations, :through => :trip_destinations

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trips }
    end
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @trip = Trip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/new
  # GET /trips/new.json
  def new
    @trip = Trip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/1/edit
  def edit
    @trip = Trip.find(params[:id])
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(params[:trip])

    respond_to do |format|
      if @trip.save
        # format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.html { redirect_to select_destinations_url, notice: 'Select your destinations.' }   
        format.json { render json: @trip, status: :created, location: @trip }
      else
        format.html { render action: "new" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trips/1
  # PUT /trips/1.json
  def update
    @trip = Trip.find(params[:id])

    respond_to do |format|
      if @trip.update_attributes(params[:trip])
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :trip_name %><br />
    <%= f.text_field :trip_name %>
  </div>
  <div class="field">
    <%= f.label :trip_description %><br />
    <%= f.text_field :trip_description %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.text_field :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.text_field :end_date %>
  </div>
  <div class="field">
    <%= f.label :creator %><br />
    <%= f.text_field :creator %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<h1>Listing trips</h1>

<table>
  <tr>
    <th>Trip name</th>
    <th>Trip description</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Creator</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trips.each do |trip| %>
  <tr>
    <td><%= trip.trip_name %></td>
    <td><%= trip.trip_description %></td>
    <td><%= trip.start_date %></td>
    <td><%= trip.end_date %></td>
    <td><%= trip.creator %></td>
    <td><%= trip.user_id %></td>
    <td><%= link_to 'Show', trip %></td>
    <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
    <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>New trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Trip name:</b>
  <%= @trip.trip_name %>
</p>

<p>
  <b>Trip description:</b>
  <%= @trip.trip_description %>
</p>

<p>
  <b>Start date:</b>
  <%= @trip.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @trip.end_date %>
</p>

<p>
  <b>Creator:</b>
  <%= @trip.creator %>
</p>

<p>
  <b>User:</b>
  <%= @trip.user_id %>
</p>


<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>