config/routes.rb
Travelpatch::Application.routes.draw do
  resources :trip_destinations
  resources :trips
  resources :destinations

  get "users/new"

  get "users/create"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "trips/index"

  get "destinations/index"

  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "trip_list" => "trips#index", :as => "trip_list"

  get "select_destinations" => "destinations#index", :as => "select_destinations"

  root :to => "users#new"

  resources :users
  resources :sessions
end

app/models/trip_destination.rb
class TripDestination < ActiveRecord::Base
  attr_accessible :destination_id, :trip_id

  belongs_to :trip
  belongs_to :destination 
end

app/controllers/trip_destinations_controller.rb
class TripDestinationsController < ApplicationController
  # GET /trip_destinations
  # GET /trip_destinations.json
  def index
    @trip_destinations = TripDestination.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trip_destinations }
    end
  end

  # GET /trip_destinations/1
  # GET /trip_destinations/1.json
  def show
    @trip_destination = TripDestination.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trip_destination }
    end
  end

  # GET /trip_destinations/new
  # GET /trip_destinations/new.json
  def new
    @trip_destination = TripDestination.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trip_destination }
    end
  end

  # GET /trip_destinations/1/edit
  def edit
    @trip_destination = TripDestination.find(params[:id])
  end

  # POST /trip_destinations
  # POST /trip_destinations.json
  def create
    @trip_destination = TripDestination.new(params[:trip_destination])

    respond_to do |format|
      if @trip_destination.save
        format.html { redirect_to @trip_destination, notice: 'Trip destination was successfully created.' }
        format.json { render json: @trip_destination, status: :created, location: @trip_destination }
      else
        format.html { render action: "new" }
        format.json { render json: @trip_destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trip_destinations/1
  # PUT /trip_destinations/1.json
  def update
    @trip_destination = TripDestination.find(params[:id])

    respond_to do |format|
      if @trip_destination.update_attributes(params[:trip_destination])
        format.html { redirect_to @trip_destination, notice: 'Trip destination was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trip_destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trip_destinations/1
  # DELETE /trip_destinations/1.json
  def destroy
    @trip_destination = TripDestination.find(params[:id])
    @trip_destination.destroy

    respond_to do |format|
      format.html { redirect_to trip_destinations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/trip_destinations_helper.rb
module TripDestinationsHelper
end

app/views/trip_destinations/_form.html.erb
<%= form_for(@trip_destination) do |f| %>
  <% if @trip_destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip_destination.errors.count, "error") %> prohibited this trip_destination from being saved:</h2>

      <ul>
      <% @trip_destination.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :destination_id %><br />
    <%= f.number_field :destination_id %>
  </div>
  <div class="field">
    <%= f.label :trip_id %><br />
    <%= f.number_field :trip_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trip_destinations/edit.html.erb
<h1>Editing trip_destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip_destination %> |
<%= link_to 'Back', trip_destinations_path %>

app/views/trip_destinations/index.html.erb
<h1>Listing trip_destinations</h1>

<table>
  <tr>
    <th>Destination</th>
    <th>Trip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trip_destinations.each do |trip_destination| %>
  <tr>
    <td><%= trip_destination.destination_id %></td>
    <td><%= trip_destination.trip_id %></td>
    <td><%= link_to 'Show', trip_destination %></td>
    <td><%= link_to 'Edit', edit_trip_destination_path(trip_destination) %></td>
    <td><%= link_to 'Destroy', trip_destination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Trip destination', new_trip_destination_path %>

app/views/trip_destinations/new.html.erb
<h1>New trip_destination</h1>

<%= render 'form' %>

<%= link_to 'Back', trip_destinations_path %>

app/views/trip_destinations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Destination:</b>
  <%= @trip_destination.destination_id %>
</p>

<p>
  <b>Trip:</b>
  <%= @trip_destination.trip_id %>
</p>


<%= link_to 'Edit', edit_trip_destination_path(@trip_destination) %> |
<%= link_to 'Back', trip_destinations_path %>