config/routes.rb
Travelpatch::Application.routes.draw do
  resources :trip_destinations
  resources :trips
  resources :destinations

  get "users/new"

  get "users/create"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "trips/index"

  get "destinations/index"

  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "trip_list" => "trips#index", :as => "trip_list"

  get "select_destinations" => "destinations#index", :as => "select_destinations"

  root :to => "users#new"

  resources :users
  resources :sessions
end

app/models/destination.rb
class Destination < ActiveRecord::Base
  attr_accessible :description, :location, :name, :rating, :picture

  has_many :trips

  has_attached_file :picture
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  # GET /destinations
  # GET /destinations.json
  def index
    @destinations = Destination.paginate(:page => params[:page], :per_page => 3)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @destinations }
    end
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
    @destination = Destination.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @destination }
    end
  end

  # GET /destinations/new
  # GET /destinations/new.json
  def new
    @destination = Destination.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @destination }
    end
  end

  # GET /destinations/1/edit
  def edit
    @destination = Destination.find(params[:id])
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(params[:destination])

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render json: @destination, status: :created, location: @destination }
      else
        format.html { render action: "new" }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /destinations/1
  # PUT /destinations/1.json
  def update
    @destination = Destination.find(params[:id])

    respond_to do |format|
      if @destination.update_attributes(params[:destination])
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination = Destination.find(params[:id])
    @destination.destroy

    respond_to do |format|
      format.html { redirect_to destinations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/_form.html.erb
<%= form_for(@destination, :html => { :multipart => true}) do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :picture %>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Editing destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<h1>Listing destinations</h1>

<%= will_paginate @destinations %>
<table>
  <tr>
    <th>&nbsp;</th>
    <th>Name</th>
    <th>Description</th>
    <th>Location</th>
    <th>Rating</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @destinations.each do |destination| %>
  <tr>
    <td><%= check_box_tag "destinations_id[]", destination.id %></td>
    <td><%= destination.name %></td>
    <td><%= destination.description %></td>
    <td><%= destination.location %></td>
    <td><%= destination.rating %></td>
    <td><%= link_to 'Show', destination %></td>
    <td><%= link_to 'Edit', edit_destination_path(destination) %></td>
    <td><%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= will_paginate @destinations, { :previous_label => "Back" } %>

<br />

<%= link_to 'New Destination', new_destination_path %>

app/views/destinations/new.html.erb
<h1>New destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @destination.name %>
</p>

<p>
  <b>Description:</b>
  <%= @destination.description %>
</p>

<p>
  <b>Location:</b>
  <%= @destination.location %>
</p>

<p>
  <b>Rating:</b>
  <%= @destination.rating %>
</p>

<%= image_tag @destination.picture.url %>

<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=New+York,+NY&amp;aq=0&amp;oq=new+york&amp;sll=40.697488,-73.979681&amp;sspn=0.630955,1.128845&amp;ie=UTF8&amp;hq=&amp;hnear=New+York&amp;ll=40.697299,-73.979187&amp;spn=0.630797,1.128845&amp;t=m&amp;z=10&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=New+York,+NY&amp;aq=0&amp;oq=new+york&amp;sll=40.697488,-73.979681&amp;sspn=0.630955,1.128845&amp;ie=UTF8&amp;hq=&amp;hnear=New+York&amp;ll=40.697299,-73.979187&amp;spn=0.630797,1.128845&amp;t=m&amp;z=10" style="color:#0000FF;text-align:left">View Larger Map</a></small>

<%= link_to 'Edit', edit_destination_path(@destination) %> |
<%= link_to 'Back', destinations_path %>