config/routes.rb
Travelpatch::Application.routes.draw do
  resources :trip_destinations
  resources :trips
  resources :destinations

  get "users/new"

  get "users/create"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "trips/index"

  get "destinations/index"

  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "trip_list" => "trips#index", :as => "trip_list"

  get "select_destinations" => "destinations#index", :as => "select_destinations"

  root :to => "users#new"

  resources :users
  resources :sessions
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tripstitch</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>
</head>
<body>

<div id = "user_nav">
	<img src="assets/travelpatch.jpg" alt="Travel Patch" width="35" height="35">
	<div id = "banner">Travel Patch</div>
	<div id = "account_status">
		<% if current_user %>
			Logged in as <%= current_user.email %>
			<%= link_to "Log Out", log_out_path %>
		<% else %>
			<%= link_to "Sign up", sign_up_path %>
			<%= link_to "Log in", log_in_path %>
		<% end %>
	</div>
</div>


<div id = "container">
	<% flash.each do |name, msg| %>
	    <%= content_tag :div, msg, :id => "flash_#{name}" %>
	<% end %>

	<%= yield %>

	<div id="footer">
		<a href="#">
			<img src="assets/social-icon-twitter.png" alt="Twitter">
		</a>
		<a href="#">
			<img src="assets/social-icon-facebook.png" alt="Facebook">
		</a>
		<a href="#">
			<img src="assets/social-icon-pinterest.png" alt="Pinterest">		
		</a>
	</div>
</div>

</body>
</html>